'''f=open('new.txt','a')
str=input()
f.write(str)
f.close()
str=f.newline()
print(str)'''
'''f=open('new.txt','a+')
f.write(str)
f.seek(0,2)
print(str)
f.close()'''

'''f=open('new.txt','a+')
str= f.read()
str1=f.readlines()
xl=line(str1)
'''for i in str:
 x=i.split()
 print(count)'''
''' when evwr a exception occur the progarm stops the execution and thus tha further code not going to execute therefore an excetion is a run time error that are anable to handle by the python
the common exception are 
1- ZeroDivisionEreror- occus when a num. is divided by zero
2- NameError- occurs when the name is not defined
3- IoError - when input and output not defined 
4- EOFError- Eccors when the end of file is reached and still operation is preform'''

